### ISSUE TITLE
Igame scroll doesnt work

### ISSUE THREAD

**Issue by franeti** [sq7bti/AmigaPS2Mouse#1]
Hi!

ussing Caffeine OS based on Workbench 3.9 i have installed your driver. For workbench “things” works fine. 

For apps like IGame or ibrowse the scroll doesnt work. 

A backer from the tank mouse project says:

MuiWheel14.Iha from Aminet too. Without this the new TankMouse driver don't work correct with OS3.9.

Is it possible to merge to install only your driver?

thanks!!!

**Comment by sq7bti** [comment]
Please run [RawKeys](http://aminet.net/package/dev/moni/Rawkeys) and confirm the (im-)proper signals produced by the driver. Are you using any other software that runs in the background and modifies the behavior of a wheel mouse (such as [FreeWheel](http://aminet.net/package/util/mouse/FreeWheel))?
Try removing MUIWheel and see if it helps.
